### ISSUE TITLE
request to add more release maintainer to libuvc-release and libubv_ros-release

### ISSUE THREAD

**Issue by k-okada** [ros-drivers-gbp/libuvc-release#4]
@oros-drivers-gbp/owners @wjwwood @awesomebytes  can you give @7675t write permission of the https://github.com/ros-drivers-gbp/libuvc-release and   https://github.com/ros-drivers-gbp/libuvc_ros-release ? 
We have discussed newer version of libuvc and now it's ready to release.
https://github.com/ktossell/libuvc/issues/86#issuecomment-331233498

**Comment by wjwwood** [comment]
I added @7675t.

**Comment by k-okada** [comment]
Thank you for super quick response!

**Comment by 7675t** [comment]
Thanks!

**Comment by 7675t** [comment]
@wjwwood Thank you, but can you give me write access to all packages including camera_drivers? specially libuvc-release and libuvc_ros-release? 

![screenshot from 2017-10-05 15-15-33](https://user-images.githubusercontent.com/25698961/31213189-3a4536ea-a9e0-11e7-81fc-a89e00dfabbf.png)
