### ISSUE TITLE
request to add write permission release maintainer to libuvc-release and libubv_ros-release

### ISSUE THREAD

**Issue by k-okada** [ros-drivers-gbp/libuvc-release#6]
@wjwwood sorry to bother you again and again. Can you add 'write permission' to @7675t (and others) for camera driver release packages? It seems some package is 'readable' ,but not 'writable'

https://github.com/ros-drivers-gbp/libuvc-release/issues/4#issuecomment-333777126

![31213189-3a4536ea-a9e0-11e7-81fc-a89e00dfabbf](https://user-images.githubusercontent.com/493276/31363813-fe353258-ad9b-11e7-9baf-b91ff11705c4.png)

**Comment by wjwwood** [comment]
Should be done now.
